#!/bin/bash

# Start/stop/restart tomcat service
# Called with 0 arguments will start a stopped service
# or stop a running service.  You can also specify
# start/stop/restart to get the expected action
function tomcat 
{
    argc=$#

    case $argc in
        0)
            sudo /usr/sbin/service tomcat6 status >/dev/null 2>&1
            if (( $? == 0 )); then
                sudo /usr/sbin/service tomcat6 stop
            else
                sudo /usr/sbin/service tomcat6 start
            fi
            ;;
        1)
            sudo /usr/sbin/service tomcat6 $*
            ;;
        *)
            echo "Not a valid option...."
            echo "Usage: tomcat [start|stop|restart]"
            ;;
    esac
}
alias t='tomcat'

# Fuzzy cd
# Usage:
#    cdf public
# Changes to repos-public directory.
# http://dpaste.org/P59h/
function cdf
{
    cd *$1*/
}

# shortcut to kill all current ssh sessions
# depends on psg
# TODO: Needs to be tested on ubuntu
function killssh 
{ 
    /usr/bin/which psg >/dev/null 2>&1
    if (( $? != 0 )); then
        echo "psg does not exist on this sytem!"
        exit 1
    fi

    for i in $(psg ssh | grep -vE "agent|UID" | tr ' ' '_') 
    do
        echo "Killing PID => $(echo $i | awk -F_ '!/UID/ {if ($6 == "") print $7; else print $6; }')..." 
        echo $i | awk -F_ '!/UID/ {if ($6 == "") print $7; else print $6; }' | xargs kill 
    done 
}

function fullBuild
{
    tomcat status >/dev/null 2>&1
    if (( $? == 0 )); then
        tomcat stop
    fi

    mypwd=$(pwd)
    cd /home/djohnston/projects/mve
    ./gradlew clean && ./gradlew platform:dm-mve:build && tomcat start
    cd $mypwd
    echo "Ready to test..."
}

# TODO: cleanup function and add persist or not option
function pm
{
    app=$1
    outDir=/home/djohnston/man_pdfs
    pushd $outDir
    man -t $app | ps2pdf - "${app}.pdf"
    /usr/bin/gnome-open "${outDir}/${app}.pdf"
    popd
}

# TODO: write doc comments
function leave_alert 
{
    when=$1
    # TODO: Write function to use at to call notify-send to send critical notification to leave!
}

function remind_me 
{
    echo 'test'
    # TODO: Write function to accept time and note to send critical notification at specific time with reminder
}

