# .bashrc
#
# if not running interactively, don't do anything
[ -z "$PS1" ] && return

# Enable vi mode
set -o vi

# History preferences
HISTCONTROL=erasedups
HISTSIZE=10000
shopt -s histappend # append instead of overwrite history

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# if this is an xterm or rxvt terminal, set window title
case "$TERM" in
xterm*|rxvt*)
    export PS1="\[\e]0;${VIRTUAL_ENV:+${debian_chroot:+($debian_chroot)}}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable bash command completion
test -f /etc/bash_completion && ! shopt -oq posix && . /etc/bash_completion

# load aliases
test -f ~/.bash_aliases && . ~/.bash_aliases

# load functions
test -f ~/.bash_functions && . ~/.bash_functions

# load virtualenvwrapper tools
. /usr/local/bin/virtualenvwrapper.sh
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true

# scripts
. $dotfiles/scripts/shtools/git-completion.bash
. $dotfiles/scripts/shtools/tmuxinator_completion

# activate autoenv first
. ~/.autoenv/activate.sh

# THEN rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
# and now rvm's after_cd hook will invoke autoenv_init

# OS-specific settings
case "$OSTYPE" in

    linux-gnu)
        ;;

    darwin*)
        # load mac-specific functions
        . $dotfiles/main/mac/functions
        ;;

    cygwin)
        ;;

    freebsd)
        ;;

esac

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
