" Vim mode
set nocompatible

" Hide buffers, don't close them
set hidden

" Initialize vundle plugin manager
let vundle_installed=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
    echo "Installing Vundle..."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
    let vundle_installed=0
endif

filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" begin: vundle plugins
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Fuzzy file search
Bundle 'kien/ctrlp.vim'
let g:ctrlp_map = '<leader>f'
" <F5> - refresh

" Easier navigation
Bundle 'Lokaltog/vim-easymotion'

" Git integration
Bundle 'tpope/vim-fugitive'

" Color-code test results
Bundle 'reinh/vim-makegreen'

" JSHint
" Bundle 'wookiehangover/jshint.vim'

" Bundle 'walm/jshint.vim'

" Comment helpers
" Bundle 'scrooloose/nerdcommenter'

" File browsing
Bundle 'scrooloose/nerdtree'
map <C-d> :NERDTreeToggle<CR>
if argc() == 0
    autocmd VimEnter * NERDTree
end

" Line numbers
Bundle 'myusuf3/numbers.vim'
" toggle absolute/relative line numbers
map <C-n> :call g:ToggleLineNumberMode()<CR>

" Python helpers
Bundle 'mattcaldwell/python-mode'
let g:pymode_folding = 0
let g:pymode_lint_ignore = "E125,E126,E127,E128,E201,E202,E225,E226,E227,E228,E231,E301,E302,E502"
let g:pymode_lint_maxlinelength = 119
map <leader>j :RopeGotoDefinition<CR>
" Add the virtualenv's site-packages to vim path
py << EOF
import os.path
import sys
import vim
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    sys.path.insert(0, project_base_dir)
    activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF

" Github commenting
Bundle 'mattcaldwell/vim-github-comment'
let g:github_user = "mattcaldwell"

" Surroundings
Bundle 'tpope/vim-surround'

" Tagbar
" Bundle 'majutsushi/tagbar'
map <C-t> :TagbarToggle<CR>

" Highlight trailing whitespace
Bundle 'bronson/vim-trailing-whitespace'

" Custom color scheme
Bundle 'twilight'

" Visual indentation guide
Bundle 'nathanaelkane/vim-indent-guides'
:let g:indent_guides_guide_size = 1
:let g:indent_guides_start_level = 2

" ???
Bundle 'MarcWeber/vim-addon-mw-utils'

" ???
Bundle 'tomtom/tlib_vim'

" TextMate-like snippets
Bundle 'garbas/vim-snipmate'

" Command completion
Bundle 'Valloric/YouCompleteMe'

" HTML/XML tags
Bundle 'Valloric/MatchTagAlways'
" match html tags (MatchTagsAlways)
let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml': 1,
    \ 'xml' : 1,
    \ 'htmldjango' : 1,
    \}

" Markdown support
Bundle 'plasticboy/vim-markdown'
let g:vim_markdown_folding_disabled=1
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" end: vundle plugins
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


" Install Vundle
if vundle_installed == 0
    echo "Installing Bundles, please ignore kep map error messages"
    echo ""
    :BundleInstall
endif

" Functions
" TODO: do i still need this?
function! g:ToggleLineNumberMode()
    if(&nu==1)
        set rnu
    elseif(&rnu==1)
        set nornu
    else
        set nu
    endif
endfunc

" Indent based on filetype
filetype plugin indent on

" Syntax highlighting and color scheme
syntax on
colorscheme twilight
highlight Pmenu ctermfg=0 ctermbg=2
highlight PmenuSel ctermfg=0 ctermbg=7

" Customize leader
let mapleader = ','

" Autocompletion
" 'YouCompleteMe' takes care of this.
"if has('autocmd')
"    autocmd FileType python set omnifunc=pythoncomplete#Complete
"    autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
"    autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
"    autocmd FileType css set omnifunc=csscomplete#CompleteCSS
"endif
"set completeopt=menuone,longest,preview

" Basic editor settings (and PEP8)
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set autoindent
set copyindent
set ignorecase
set smartcase
set smarttab
set nowrap
set cursorline
set backspace=indent,eol,start
set encoding=utf-8

set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc,*.class
set title
set visualbell
set noerrorbells

" Backups and swap files
silent !mkdir ~/tmp > /dev/null 2>&1
set backup
set swapfile
set backupdir=~/tmp
set dir=~/tmp

" Mappings -----------------------------------------
"
" display tags
" clear highlighting
map <C-g> :noh<CR>
" clear search
map <C-s> :let @/ = ""<CR>
" toggle list
map <C-l> :set list!<CR>
" django tests
map <leader>dt :set makeprg=python\ manage.py\ test\|:call MakeGreen()<CR>
" django server
map <leader>rs :set makeprg=python\ manage.py\ runserver<CR>
" nose tests
map <leader>rt :!nosetests --with-coverage<CR>
" window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
"
" End Mappings -------------------------------------

" Status Line
set statusline=%t       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%{exists('g:loaded_fugitive')?fugitive#statusline():''} " git branch
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file
set laststatus=2

" search/replace
set hlsearch
set incsearch
map <leader>n :cn<CR>
map <leader>p :cp<CR>

" Whitespace
set list
set listchars=tab:▷⋅,trail:⋅,nbsp:⋅
if has('autocmd')
    autocmd filetype html,xml set listchars-=tab:>.
endif

" Toggle paste mode
set pastetoggle=<F2>

" Forget to sudo?
cmap w!! w !sudo tee % >/dev/null
