## DO NOT EDIT! GENERATED AUTOMATICALLY!
## Process this file with automake to produce Makefile.in.
# Copyright (C) 2002-2010 Free Software Foundation, Inc.
#
# This file is free software, distributed under the terms of the GNU
# General Public License.  As a special exception to the GNU General
# Public License, this file may be distributed as part of a program
# that contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.

AUTOMAKE_OPTIONS = 1.5 foreign subdir-objects

SUBDIRS = .
TESTS =
XFAIL_TESTS =
TESTS_ENVIRONMENT =
noinst_PROGRAMS =
check_PROGRAMS =
noinst_HEADERS =
noinst_LIBRARIES =
check_LIBRARIES = libtests.a
EXTRA_DIST =
BUILT_SOURCES =
SUFFIXES =
MOSTLYCLEANFILES = core *.stackdump
MOSTLYCLEANDIRS =
CLEANFILES =
DISTCLEANFILES =
MAINTAINERCLEANFILES =

AM_CPPFLAGS = \
  -D@gltests_WITNESS@=1 \
  -I. -I$(srcdir) \
  -I.. -I$(srcdir)/.. \
  -I../lib -I$(srcdir)/../lib

LDADD = libtests.a ../lib/libgnu.a libtests.a $(LIBTESTS_LIBDEPS)

libtests_a_SOURCES =
libtests_a_LIBADD = $(gltests_LIBOBJS)
libtests_a_DEPENDENCIES = $(gltests_LIBOBJS)
EXTRA_libtests_a_SOURCES =
AM_LIBTOOLFLAGS = --preserve-dup-deps

TESTS_ENVIRONMENT += EXEEXT='@EXEEXT@' srcdir='$(srcdir)'

## begin gnulib module alloca-opt-tests

TESTS += test-alloca-opt
check_PROGRAMS += test-alloca-opt

EXTRA_DIST += test-alloca-opt.c

## end   gnulib module alloca-opt-tests

## begin gnulib module arg-nonnull

# The BUILT_SOURCES created by this Makefile snippet are not used via #include
# statements but through direct file reference. Therefore this snippet must be
# present in all Makefile.am that need it. This is ensured by the applicability
# 'all' defined above.

BUILT_SOURCES += arg-nonnull.h
# The arg-nonnull.h that gets inserted into generated .h files is the same as
# build-aux/arg-nonnull.h, except that it has the copyright header cut off.
arg-nonnull.h: $(top_srcdir)/build-aux/arg-nonnull.h
	$(AM_V_GEN)rm -f $@-t $@ && \
	sed -n -e '/GL_ARG_NONNULL/,$$p' \
	  < $(top_srcdir)/build-aux/arg-nonnull.h \
	  > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += arg-nonnull.h arg-nonnull.h-t

ARG_NONNULL_H=arg-nonnull.h

EXTRA_DIST += $(top_srcdir)/build-aux/arg-nonnull.h

## end   gnulib module arg-nonnull

## begin gnulib module argmatch


EXTRA_DIST += argmatch.c argmatch.h

EXTRA_libtests_a_SOURCES += argmatch.c

## end   gnulib module argmatch

## begin gnulib module argmatch-tests

TESTS += test-argmatch
check_PROGRAMS += test-argmatch
test_argmatch_LDADD = $(LDADD) @LIBINTL@

EXTRA_DIST += test-argmatch.c macros.h

## end   gnulib module argmatch-tests

## begin gnulib module argv-iter-tests

TESTS += test-argv-iter
check_PROGRAMS += test-argv-iter
EXTRA_DIST += test-argv-iter.c macros.h

## end   gnulib module argv-iter-tests

## begin gnulib module binary-io

libtests_a_SOURCES += binary-io.h

## end   gnulib module binary-io

## begin gnulib module binary-io-tests

TESTS += test-binary-io.sh
check_PROGRAMS += test-binary-io

EXTRA_DIST += test-binary-io.sh test-binary-io.c macros.h

## end   gnulib module binary-io-tests

## begin gnulib module bitrotate-tests

TESTS += test-bitrotate
check_PROGRAMS += test-bitrotate
EXTRA_DIST += test-bitrotate.c macros.h

## end   gnulib module bitrotate-tests

## begin gnulib module btowc-tests

TESTS += test-btowc1.sh test-btowc2.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-btowc

EXTRA_DIST += test-btowc1.sh test-btowc2.sh test-btowc.c signature.h macros.h

## end   gnulib module btowc-tests

## begin gnulib module c++defs

# The BUILT_SOURCES created by this Makefile snippet are not used via #include
# statements but through direct file reference. Therefore this snippet must be
# present in all Makefile.am that need it. This is ensured by the applicability
# 'all' defined above.

BUILT_SOURCES += c++defs.h
# The c++defs.h that gets inserted into generated .h files is the same as
# build-aux/c++defs.h, except that it has the copyright header cut off.
c++defs.h: $(top_srcdir)/build-aux/c++defs.h
	$(AM_V_GEN)rm -f $@-t $@ && \
	sed -n -e '/_GL_CXXDEFS/,$$p' \
	  < $(top_srcdir)/build-aux/c++defs.h \
	  > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += c++defs.h c++defs.h-t

CXXDEFS_H=c++defs.h

EXTRA_DIST += $(top_srcdir)/build-aux/c++defs.h

## end   gnulib module c++defs

## begin gnulib module c-ctype

libtests_a_SOURCES += c-ctype.h c-ctype.c

## end   gnulib module c-ctype

## begin gnulib module c-ctype-tests

TESTS += test-c-ctype
check_PROGRAMS += test-c-ctype

EXTRA_DIST += test-c-ctype.c macros.h

## end   gnulib module c-ctype-tests

## begin gnulib module c-strcase

libtests_a_SOURCES += c-strcase.h c-strcasecmp.c c-strncasecmp.c

## end   gnulib module c-strcase

## begin gnulib module c-strcase-tests

TESTS += test-c-strcase.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_TR_UTF8='@LOCALE_TR_UTF8@'
check_PROGRAMS += test-c-strcasecmp test-c-strncasecmp
EXTRA_DIST += test-c-strcase.sh test-c-strcasecmp.c test-c-strncasecmp.c macros.h

## end   gnulib module c-strcase-tests

## begin gnulib module chown-tests

TESTS += test-chown
check_PROGRAMS += test-chown
test_chown_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += nap.h test-chown.h test-chown.c signature.h macros.h

## end   gnulib module chown-tests

## begin gnulib module cloexec-tests

TESTS += test-cloexec
check_PROGRAMS += test-cloexec
EXTRA_DIST += test-cloexec.c macros.h

## end   gnulib module cloexec-tests

## begin gnulib module dirent-tests

TESTS += test-dirent
check_PROGRAMS += test-dirent
EXTRA_DIST += test-dirent.c

## end   gnulib module dirent-tests

## begin gnulib module dirname-tests

TESTS += test-dirname
check_PROGRAMS += test-dirname
test_dirname_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-dirname.c

## end   gnulib module dirname-tests

## begin gnulib module dup2-tests

TESTS += test-dup2
check_PROGRAMS += test-dup2
EXTRA_DIST += test-dup2.c signature.h macros.h

## end   gnulib module dup2-tests

## begin gnulib module environ-tests

TESTS += test-environ
check_PROGRAMS += test-environ

EXTRA_DIST += test-environ.c

## end   gnulib module environ-tests

## begin gnulib module errno-tests

TESTS += test-errno
check_PROGRAMS += test-errno

EXTRA_DIST += test-errno.c

## end   gnulib module errno-tests

## begin gnulib module exclude-tests

TESTS += \
 test-exclude1.sh\
 test-exclude2.sh\
 test-exclude3.sh\
 test-exclude4.sh\
 test-exclude5.sh\
 test-exclude6.sh\
 test-exclude7.sh\
 test-exclude8.sh

check_PROGRAMS += test-exclude
test_exclude_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-exclude.c test-exclude1.sh test-exclude2.sh test-exclude3.sh test-exclude4.sh test-exclude5.sh test-exclude6.sh test-exclude7.sh test-exclude8.sh

## end   gnulib module exclude-tests

## begin gnulib module fchdir-tests

TESTS += test-fchdir
check_PROGRAMS += test-fchdir
EXTRA_DIST += test-fchdir.c signature.h macros.h

## end   gnulib module fchdir-tests

## begin gnulib module fcntl-h-tests

TESTS += test-fcntl-h
check_PROGRAMS += test-fcntl-h
EXTRA_DIST += test-fcntl-h.c

## end   gnulib module fcntl-h-tests

## begin gnulib module fcntl-tests

TESTS += test-fcntl
check_PROGRAMS += test-fcntl
EXTRA_DIST += test-fcntl.c signature.h macros.h

## end   gnulib module fcntl-tests

## begin gnulib module fd-safer-flag

libtests_a_SOURCES += fd-safer-flag.c dup-safer-flag.c

## end   gnulib module fd-safer-flag

## begin gnulib module fdopendir-tests

TESTS += test-fdopendir
check_PROGRAMS += test-fdopendir
test_fdopendir_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-fdopendir.c signature.h macros.h

## end   gnulib module fdopendir-tests

## begin gnulib module fflush-tests

TESTS += test-fflush test-fflush2.sh
check_PROGRAMS += test-fflush test-fflush2
MOSTLYCLEANFILES += test-fflush.txt
EXTRA_DIST += test-fflush.c test-fflush2.sh test-fflush2.c signature.h macros.h

## end   gnulib module fflush-tests

## begin gnulib module fnmatch-tests

TESTS += test-fnmatch
check_PROGRAMS += test-fnmatch
EXTRA_DIST += test-fnmatch.c signature.h macros.h

## end   gnulib module fnmatch-tests

## begin gnulib module fopen-tests

TESTS += test-fopen
check_PROGRAMS += test-fopen

EXTRA_DIST += test-fopen.h test-fopen.c signature.h macros.h

## end   gnulib module fopen-tests

## begin gnulib module fpending-tests

TESTS += test-fpending.sh
check_PROGRAMS += test-fpending
MOSTLYCLEANFILES += test-fpending.t
EXTRA_DIST += test-fpending.c test-fpending.sh macros.h

## end   gnulib module fpending-tests

## begin gnulib module fprintf-posix-tests

TESTS += test-fprintf-posix.sh test-fprintf-posix2.sh test-fprintf-posix3.sh
check_PROGRAMS += test-fprintf-posix test-fprintf-posix2 test-fprintf-posix3
EXTRA_DIST += test-fprintf-posix.sh test-fprintf-posix.c test-fprintf-posix.h test-printf-posix.output test-fprintf-posix2.sh test-fprintf-posix2.c test-fprintf-posix3.sh test-fprintf-posix3.c signature.h macros.h

## end   gnulib module fprintf-posix-tests

## begin gnulib module fpurge-tests

TESTS += test-fpurge
check_PROGRAMS += test-fpurge
MOSTLYCLEANFILES += t-fpurge.tmp
EXTRA_DIST += test-fpurge.c macros.h

## end   gnulib module fpurge-tests

## begin gnulib module freading-tests

TESTS += test-freading
check_PROGRAMS += test-freading
MOSTLYCLEANFILES += t-freading.tmp
EXTRA_DIST += test-freading.c macros.h

## end   gnulib module freading-tests

## begin gnulib module freopen-tests

TESTS += test-freopen
check_PROGRAMS += test-freopen

EXTRA_DIST += test-freopen.c signature.h macros.h

## end   gnulib module freopen-tests

## begin gnulib module frexp-nolibm-tests

TESTS += test-frexp-nolibm
check_PROGRAMS += test-frexp-nolibm
test_frexp_nolibm_SOURCES = test-frexp.c
EXTRA_DIST += test-frexp.c signature.h macros.h

## end   gnulib module frexp-nolibm-tests

## begin gnulib module frexpl-nolibm-tests

TESTS += test-frexpl-nolibm
check_PROGRAMS += test-frexpl-nolibm
test_frexpl_nolibm_SOURCES = test-frexpl.c
EXTRA_DIST += test-frexpl.c signature.h macros.h

## end   gnulib module frexpl-nolibm-tests

## begin gnulib module fseeko-tests

TESTS += test-fseeko.sh test-fseeko2.sh
check_PROGRAMS += test-fseeko
EXTRA_DIST += test-fseeko.c test-fseeko.sh test-fseeko2.sh signature.h macros.h

## end   gnulib module fseeko-tests

## begin gnulib module fseterr-tests

TESTS += test-fseterr
check_PROGRAMS += test-fseterr

EXTRA_DIST += test-fseterr.c

## end   gnulib module fseterr-tests

## begin gnulib module ftell


EXTRA_DIST += ftell.c

EXTRA_libtests_a_SOURCES += ftell.c

## end   gnulib module ftell

## begin gnulib module ftell-tests

TESTS += test-ftell.sh test-ftell2.sh test-ftell3
check_PROGRAMS += test-ftell test-ftell3
MOSTLYCLEANFILES += t-ftell3.tmp
EXTRA_DIST += test-ftell.c test-ftell.sh test-ftell2.sh test-ftell3.c signature.h macros.h

## end   gnulib module ftell-tests

## begin gnulib module ftello-tests

TESTS += test-ftello.sh test-ftello2.sh test-ftello3
check_PROGRAMS += test-ftello test-ftello3
MOSTLYCLEANFILES += t-ftello3.tmp
EXTRA_DIST += test-ftello.c test-ftello.sh test-ftello2.sh test-ftello3.c signature.h macros.h

## end   gnulib module ftello-tests

## begin gnulib module getcwd-tests

TESTS += test-getcwd
check_PROGRAMS += test-getcwd
EXTRA_DIST += test-getcwd.c signature.h macros.h

## end   gnulib module getcwd-tests

## begin gnulib module getdelim-tests

TESTS += test-getdelim
check_PROGRAMS += test-getdelim
MOSTLYCLEANFILES += test-getdelim.txt
EXTRA_DIST += test-getdelim.c signature.h macros.h

## end   gnulib module getdelim-tests

## begin gnulib module getdtablesize-tests

TESTS += test-getdtablesize
check_PROGRAMS += test-getdtablesize
EXTRA_DIST += test-getdtablesize.c signature.h macros.h

## end   gnulib module getdtablesize-tests

## begin gnulib module getgroups


EXTRA_DIST += getgroups.c

EXTRA_libtests_a_SOURCES += getgroups.c

## end   gnulib module getgroups

## begin gnulib module getgroups-tests

TESTS += test-getgroups
check_PROGRAMS += test-getgroups
EXTRA_DIST += test-getgroups.c signature.h macros.h

## end   gnulib module getgroups-tests

## begin gnulib module getopt-posix-tests

TESTS += test-getopt
check_PROGRAMS += test-getopt
test_getopt_LDADD = $(LDADD) $(LIBINTL)
EXTRA_DIST += macros.h signature.h test-getopt.c test-getopt.h test-getopt_long.h

## end   gnulib module getopt-posix-tests

## begin gnulib module getpagesize


EXTRA_DIST += getpagesize.c

EXTRA_libtests_a_SOURCES += getpagesize.c

## end   gnulib module getpagesize

## begin gnulib module getugroups


EXTRA_DIST += getugroups.c getugroups.h

EXTRA_libtests_a_SOURCES += getugroups.c

## end   gnulib module getugroups

## begin gnulib module hash-pjw

libtests_a_SOURCES += hash-pjw.h hash-pjw.c

## end   gnulib module hash-pjw

## begin gnulib module hash-tests

TESTS += test-hash
check_PROGRAMS += test-hash
test_hash_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-hash.c macros.h

## end   gnulib module hash-tests

## begin gnulib module inttostr-tests

TESTS += test-inttostr
check_PROGRAMS += test-inttostr
EXTRA_DIST += macros.h test-inttostr.c

## end   gnulib module inttostr-tests

## begin gnulib module inttypes

BUILT_SOURCES += inttypes.h

# We need the following in order to create <inttypes.h> when the system
# doesn't have one that works with the given compiler.
inttypes.h: inttypes.in.h $(WARN_ON_USE_H) $(ARG_NONNULL_H)
	$(AM_V_GEN)rm -f $@-t $@ && \
	{ echo '/* DO NOT EDIT! GENERATED AUTOMATICALLY! */'; \
	  sed -e 's/@''HAVE_INTTYPES_H''@/$(HAVE_INTTYPES_H)/g' \
	      -e 's|@''INCLUDE_NEXT''@|$(INCLUDE_NEXT)|g' \
	      -e 's|@''PRAGMA_SYSTEM_HEADER''@|@PRAGMA_SYSTEM_HEADER@|g' \
	      -e 's|@''NEXT_INTTYPES_H''@|$(NEXT_INTTYPES_H)|g' \
	      -e 's/@''PRI_MACROS_BROKEN''@/$(PRI_MACROS_BROKEN)/g' \
	      -e 's/@''APPLE_UNIVERSAL_BUILD''@/$(APPLE_UNIVERSAL_BUILD)/g' \
	      -e 's/@''HAVE_LONG_LONG_INT''@/$(HAVE_LONG_LONG_INT)/g' \
	      -e 's/@''HAVE_UNSIGNED_LONG_LONG_INT''@/$(HAVE_UNSIGNED_LONG_LONG_INT)/g' \
	      -e 's/@''PRIPTR_PREFIX''@/$(PRIPTR_PREFIX)/g' \
	      -e 's/@''GNULIB_IMAXABS''@/$(GNULIB_IMAXABS)/g' \
	      -e 's/@''GNULIB_IMAXDIV''@/$(GNULIB_IMAXDIV)/g' \
	      -e 's/@''GNULIB_STRTOIMAX''@/$(GNULIB_STRTOIMAX)/g' \
	      -e 's/@''GNULIB_STRTOUMAX''@/$(GNULIB_STRTOUMAX)/g' \
	      -e 's/@''HAVE_DECL_IMAXABS''@/$(HAVE_DECL_IMAXABS)/g' \
	      -e 's/@''HAVE_DECL_IMAXDIV''@/$(HAVE_DECL_IMAXDIV)/g' \
	      -e 's/@''HAVE_DECL_STRTOIMAX''@/$(HAVE_DECL_STRTOIMAX)/g' \
	      -e 's/@''HAVE_DECL_STRTOUMAX''@/$(HAVE_DECL_STRTOUMAX)/g' \
	      -e 's/@''INT32_MAX_LT_INTMAX_MAX''@/$(INT32_MAX_LT_INTMAX_MAX)/g' \
	      -e 's/@''INT64_MAX_EQ_LONG_MAX''@/$(INT64_MAX_EQ_LONG_MAX)/g' \
	      -e 's/@''UINT32_MAX_LT_UINTMAX_MAX''@/$(UINT32_MAX_LT_UINTMAX_MAX)/g' \
	      -e 's/@''UINT64_MAX_EQ_ULONG_MAX''@/$(UINT64_MAX_EQ_ULONG_MAX)/g' \
	      -e '/definition of _GL_ARG_NONNULL/r $(ARG_NONNULL_H)' \
	      -e '/definition of _GL_WARN_ON_USE/r $(WARN_ON_USE_H)' \
	      < $(srcdir)/inttypes.in.h; \
	} > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += inttypes.h inttypes.h-t

EXTRA_DIST += inttypes.in.h

## end   gnulib module inttypes

## begin gnulib module inttypes-tests

TESTS += test-inttypes
check_PROGRAMS += test-inttypes
EXTRA_DIST += test-inttypes.c

## end   gnulib module inttypes-tests

## begin gnulib module isnand-nolibm-tests

TESTS += test-isnand-nolibm
check_PROGRAMS += test-isnand-nolibm

EXTRA_DIST += test-isnand-nolibm.c test-isnand.h nan.h macros.h

## end   gnulib module isnand-nolibm-tests

## begin gnulib module isnanf-nolibm-tests

TESTS += test-isnanf-nolibm
check_PROGRAMS += test-isnanf-nolibm

EXTRA_DIST += test-isnanf-nolibm.c test-isnanf.h nan.h macros.h

## end   gnulib module isnanf-nolibm-tests

## begin gnulib module isnanl-nolibm-tests

TESTS += test-isnanl-nolibm
check_PROGRAMS += test-isnanl-nolibm

EXTRA_DIST += test-isnanl-nolibm.c test-isnanl.h nan.h macros.h

## end   gnulib module isnanl-nolibm-tests

## begin gnulib module langinfo-tests

TESTS += test-langinfo
check_PROGRAMS += test-langinfo
EXTRA_DIST += test-langinfo.c

## end   gnulib module langinfo-tests

## begin gnulib module lchown-tests

TESTS += test-lchown
check_PROGRAMS += test-lchown
test_lchown_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += nap.h test-lchown.h test-lchown.c signature.h macros.h

## end   gnulib module lchown-tests

## begin gnulib module lseek-tests

TESTS += test-lseek.sh
check_PROGRAMS += test-lseek
EXTRA_DIST += test-lseek.c test-lseek.sh signature.h macros.h

## end   gnulib module lseek-tests

## begin gnulib module lstat-tests

TESTS += test-lstat
check_PROGRAMS += test-lstat
EXTRA_DIST += test-lstat.h test-lstat.c signature.h macros.h

## end   gnulib module lstat-tests

## begin gnulib module malloca

libtests_a_SOURCES += malloca.c

EXTRA_DIST += malloca.h malloca.valgrind

## end   gnulib module malloca

## begin gnulib module malloca-tests

TESTS += test-malloca
check_PROGRAMS += test-malloca

EXTRA_DIST += test-malloca.c

## end   gnulib module malloca-tests

## begin gnulib module math-tests

TESTS += test-math
check_PROGRAMS += test-math
EXTRA_DIST += test-math.c

## end   gnulib module math-tests

## begin gnulib module mbrtowc-tests

TESTS += test-mbrtowc1.sh test-mbrtowc2.sh test-mbrtowc3.sh test-mbrtowc4.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-mbrtowc

EXTRA_DIST += test-mbrtowc1.sh test-mbrtowc2.sh test-mbrtowc3.sh test-mbrtowc4.sh test-mbrtowc.c signature.h macros.h

## end   gnulib module mbrtowc-tests

## begin gnulib module mbscasecmp-tests

TESTS += test-mbscasecmp.sh
TESTS_ENVIRONMENT += LOCALE_TR_UTF8='@LOCALE_TR_UTF8@'
check_PROGRAMS += test-mbscasecmp

EXTRA_DIST += test-mbscasecmp.sh test-mbscasecmp.c macros.h

## end   gnulib module mbscasecmp-tests

## begin gnulib module mbsinit-tests

TESTS += test-mbsinit.sh
TESTS_ENVIRONMENT += LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-mbsinit

EXTRA_DIST += test-mbsinit.sh test-mbsinit.c signature.h macros.h

## end   gnulib module mbsinit-tests

## begin gnulib module mbsrtowcs-tests

TESTS += test-mbsrtowcs1.sh test-mbsrtowcs2.sh test-mbsrtowcs3.sh test-mbsrtowcs4.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-mbsrtowcs

EXTRA_DIST += test-mbsrtowcs1.sh test-mbsrtowcs2.sh test-mbsrtowcs3.sh test-mbsrtowcs4.sh test-mbsrtowcs.c signature.h macros.h

## end   gnulib module mbsrtowcs-tests

## begin gnulib module memchr-tests

TESTS += test-memchr
check_PROGRAMS += test-memchr
EXTRA_DIST += test-memchr.c zerosize-ptr.h signature.h macros.h

## end   gnulib module memchr-tests

## begin gnulib module memrchr-tests

TESTS += test-memrchr
check_PROGRAMS += test-memrchr
EXTRA_DIST += test-memrchr.c zerosize-ptr.h signature.h macros.h

## end   gnulib module memrchr-tests

## begin gnulib module mgetgroups


EXTRA_DIST += mgetgroups.c mgetgroups.h

EXTRA_libtests_a_SOURCES += mgetgroups.c

## end   gnulib module mgetgroups

## begin gnulib module mkdir-tests

TESTS += test-mkdir
check_PROGRAMS += test-mkdir
EXTRA_DIST += test-mkdir.h test-mkdir.c signature.h macros.h

## end   gnulib module mkdir-tests

## begin gnulib module nl_langinfo-tests

TESTS += test-nl_langinfo.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-nl_langinfo
EXTRA_DIST += test-nl_langinfo.sh test-nl_langinfo.c signature.h macros.h

## end   gnulib module nl_langinfo-tests

## begin gnulib module open-tests

TESTS += test-open
check_PROGRAMS += test-open
EXTRA_DIST += test-open.h test-open.c signature.h macros.h

## end   gnulib module open-tests

## begin gnulib module openat-tests

TESTS += test-fchownat test-fstatat test-mkdirat test-openat test-unlinkat
check_PROGRAMS += test-fchownat test-fstatat test-mkdirat test-openat \
  test-unlinkat
test_fchownat_LDADD = $(LDADD) @LIBINTL@
test_fstatat_LDADD = $(LDADD) @LIBINTL@
test_mkdirat_LDADD = $(LDADD) @LIBINTL@
test_openat_LDADD = $(LDADD) @LIBINTL@
test_unlinkat_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += nap.h test-chown.h test-lchown.h test-lstat.h test-mkdir.h test-rmdir.h test-stat.h test-unlink.h test-fchownat.c test-fstatat.c test-mkdirat.c test-openat.c test-unlinkat.c signature.h macros.h

## end   gnulib module openat-tests

## begin gnulib module printf-frexp-tests

TESTS += test-printf-frexp
check_PROGRAMS += test-printf-frexp
EXTRA_DIST += test-printf-frexp.c macros.h

## end   gnulib module printf-frexp-tests

## begin gnulib module printf-frexpl-tests

TESTS += test-printf-frexpl
check_PROGRAMS += test-printf-frexpl
EXTRA_DIST += test-printf-frexpl.c macros.h

## end   gnulib module printf-frexpl-tests

## begin gnulib module printf-posix-tests

TESTS += test-printf-posix.sh test-printf-posix2.sh
check_PROGRAMS += test-printf-posix test-printf-posix2
EXTRA_DIST += test-printf-posix.sh test-printf-posix.c test-printf-posix.h test-printf-posix.output test-printf-posix2.sh test-printf-posix2.c signature.h macros.h

## end   gnulib module printf-posix-tests

## begin gnulib module priv-set

libtests_a_SOURCES += priv-set.c

EXTRA_DIST += priv-set.h

## end   gnulib module priv-set

## begin gnulib module priv-set-tests

TESTS += test-priv-set
check_PROGRAMS += test-priv-set
EXTRA_DIST += test-priv-set.c macros.h

## end   gnulib module priv-set-tests

## begin gnulib module putenv


EXTRA_DIST += putenv.c

EXTRA_libtests_a_SOURCES += putenv.c

## end   gnulib module putenv

## begin gnulib module quotearg-simple-tests

TESTS += test-quotearg-simple
check_PROGRAMS += test-quotearg-simple
test_quotearg_simple_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-quotearg-simple.c test-quotearg.h macros.h

## end   gnulib module quotearg-simple-tests

## begin gnulib module rmdir-tests

TESTS += test-rmdir
check_PROGRAMS += test-rmdir
EXTRA_DIST += test-rmdir.h test-rmdir.c signature.h macros.h

## end   gnulib module rmdir-tests

## begin gnulib module setenv


EXTRA_DIST += setenv.c

EXTRA_libtests_a_SOURCES += setenv.c

## end   gnulib module setenv

## begin gnulib module setenv-tests

TESTS += test-setenv
check_PROGRAMS += test-setenv
EXTRA_DIST += test-setenv.c signature.h macros.h

## end   gnulib module setenv-tests

## begin gnulib module signbit-tests

TESTS += test-signbit
check_PROGRAMS += test-signbit

EXTRA_DIST += test-signbit.c macros.h

## end   gnulib module signbit-tests

## begin gnulib module sleep


EXTRA_DIST += sleep.c

EXTRA_libtests_a_SOURCES += sleep.c

## end   gnulib module sleep

## begin gnulib module sleep-tests

TESTS += test-sleep
check_PROGRAMS += test-sleep
EXTRA_DIST += test-sleep.c signature.h macros.h

## end   gnulib module sleep-tests

## begin gnulib module snprintf


EXTRA_DIST += snprintf.c

EXTRA_libtests_a_SOURCES += snprintf.c

## end   gnulib module snprintf

## begin gnulib module snprintf-tests

TESTS += test-snprintf
check_PROGRAMS += test-snprintf

EXTRA_DIST += test-snprintf.c signature.h macros.h

## end   gnulib module snprintf-tests

## begin gnulib module sprintf-posix-tests

TESTS += test-sprintf-posix
check_PROGRAMS += test-sprintf-posix

EXTRA_DIST += test-sprintf-posix.c test-sprintf-posix.h nan.h signature.h macros.h

## end   gnulib module sprintf-posix-tests

## begin gnulib module stat-tests

TESTS += test-stat
check_PROGRAMS += test-stat
EXTRA_DIST += test-stat.h test-stat.c signature.h macros.h

## end   gnulib module stat-tests

## begin gnulib module stat-time


EXTRA_DIST += stat-time.h

## end   gnulib module stat-time

## begin gnulib module stat-time-tests

TESTS += test-stat-time
check_PROGRAMS += test-stat-time
EXTRA_DIST += test-stat-time.c macros.h

## end   gnulib module stat-time-tests

## begin gnulib module stdbool-tests

TESTS += test-stdbool
check_PROGRAMS += test-stdbool
EXTRA_DIST += test-stdbool.c

## end   gnulib module stdbool-tests

## begin gnulib module stddef-tests

TESTS += test-stddef
check_PROGRAMS += test-stddef
EXTRA_DIST += test-stddef.c

## end   gnulib module stddef-tests

## begin gnulib module stdint-tests

TESTS += test-stdint
check_PROGRAMS += test-stdint
EXTRA_DIST += test-stdint.c

## end   gnulib module stdint-tests

## begin gnulib module stdio-tests

TESTS += test-stdio
check_PROGRAMS += test-stdio
EXTRA_DIST += test-stdio.c

## end   gnulib module stdio-tests

## begin gnulib module stdlib-tests

TESTS += test-stdlib
check_PROGRAMS += test-stdlib
EXTRA_DIST += test-stdlib.c

## end   gnulib module stdlib-tests

## begin gnulib module strcasestr-tests

TESTS += test-strcasestr
check_PROGRAMS += test-strcasestr

EXTRA_DIST += test-strcasestr.c signature.h macros.h

## end   gnulib module strcasestr-tests

## begin gnulib module strerror-tests

TESTS += test-strerror
check_PROGRAMS += test-strerror
EXTRA_DIST += test-strerror.c signature.h macros.h

## end   gnulib module strerror-tests

## begin gnulib module string-tests

TESTS += test-string
check_PROGRAMS += test-string
EXTRA_DIST += test-string.c

## end   gnulib module string-tests

## begin gnulib module strings-tests

TESTS += test-strings
check_PROGRAMS += test-strings
EXTRA_DIST += test-strings.c

## end   gnulib module strings-tests

## begin gnulib module symlink


EXTRA_DIST += symlink.c

EXTRA_libtests_a_SOURCES += symlink.c

## end   gnulib module symlink

## begin gnulib module symlink-tests

TESTS += test-symlink
check_PROGRAMS += test-symlink
EXTRA_DIST += test-symlink.h test-symlink.c signature.h macros.h

## end   gnulib module symlink-tests

## begin gnulib module sys_ioctl-tests

TESTS += test-sys_ioctl
check_PROGRAMS += test-sys_ioctl
EXTRA_DIST += test-sys_ioctl.c

## end   gnulib module sys_ioctl-tests

## begin gnulib module sys_stat-tests

TESTS += test-sys_stat
check_PROGRAMS += test-sys_stat
EXTRA_DIST += test-sys_stat.c

## end   gnulib module sys_stat-tests

## begin gnulib module time-tests

TESTS += test-time
check_PROGRAMS += test-time
EXTRA_DIST += test-time.c

## end   gnulib module time-tests

## begin gnulib module unistd-safer-tests

TESTS += test-dup-safer
check_PROGRAMS += test-dup-safer
EXTRA_DIST += test-dup-safer.c macros.h

## end   gnulib module unistd-safer-tests

## begin gnulib module unistd-tests

TESTS += test-unistd
check_PROGRAMS += test-unistd
EXTRA_DIST += test-unistd.c

## end   gnulib module unistd-tests

## begin gnulib module uniwidth/width-tests

TESTS += test-uc_width uniwidth/test-uc_width2.sh
check_PROGRAMS += test-uc_width test-uc_width2
test_uc_width_SOURCES = uniwidth/test-uc_width.c
test_uc_width_LDADD = $(LDADD) $(LIBUNISTRING)
test_uc_width2_SOURCES = uniwidth/test-uc_width2.c
test_uc_width2_LDADD = $(LDADD) $(LIBUNISTRING)
EXTRA_DIST += uniwidth/test-uc_width.c uniwidth/test-uc_width2.c uniwidth/test-uc_width2.sh macros.h

## end   gnulib module uniwidth/width-tests

## begin gnulib module unlink-tests

TESTS += test-unlink
check_PROGRAMS += test-unlink
EXTRA_DIST += test-unlink.h test-unlink.c signature.h macros.h

## end   gnulib module unlink-tests

## begin gnulib module unlinkdir


EXTRA_DIST += unlinkdir.c unlinkdir.h

EXTRA_libtests_a_SOURCES += unlinkdir.c

## end   gnulib module unlinkdir

## begin gnulib module unsetenv


EXTRA_DIST += unsetenv.c

EXTRA_libtests_a_SOURCES += unsetenv.c

## end   gnulib module unsetenv

## begin gnulib module unsetenv-tests

TESTS += test-unsetenv
check_PROGRAMS += test-unsetenv
EXTRA_DIST += test-unsetenv.c signature.h macros.h

## end   gnulib module unsetenv-tests

## begin gnulib module update-copyright-tests

TESTS += test-update-copyright.sh
TESTS_ENVIRONMENT += PATH='$(abs_aux_dir)'$(PATH_SEPARATOR)"$$PATH"
EXTRA_DIST += test-update-copyright.sh

## end   gnulib module update-copyright-tests

## begin gnulib module usleep


EXTRA_DIST += usleep.c

EXTRA_libtests_a_SOURCES += usleep.c

## end   gnulib module usleep

## begin gnulib module usleep-tests

TESTS += test-usleep
check_PROGRAMS += test-usleep
EXTRA_DIST += test-usleep.c signature.h macros.h

## end   gnulib module usleep-tests

## begin gnulib module vasnprintf-tests

TESTS += test-vasnprintf
check_PROGRAMS += test-vasnprintf

EXTRA_DIST += test-vasnprintf.c macros.h

## end   gnulib module vasnprintf-tests

## begin gnulib module vc-list-files-tests

TESTS += test-vc-list-files-git.sh
TESTS += test-vc-list-files-cvs.sh
TESTS_ENVIRONMENT += PATH='$(abs_aux_dir)'$(PATH_SEPARATOR)"$$PATH"
EXTRA_DIST += test-vc-list-files-git.sh test-vc-list-files-cvs.sh init.sh

## end   gnulib module vc-list-files-tests

## begin gnulib module verify-tests

TESTS_ENVIRONMENT += MAKE='$(MAKE)'
TESTS += test-verify test-verify.sh
check_PROGRAMS += test-verify
EXTRA_DIST += test-verify.c test-verify.sh init.sh

## end   gnulib module verify-tests

## begin gnulib module vfprintf-posix-tests

TESTS += test-vfprintf-posix.sh
check_PROGRAMS += test-vfprintf-posix
EXTRA_DIST += test-vfprintf-posix.sh test-vfprintf-posix.c test-fprintf-posix.h test-printf-posix.output signature.h macros.h

## end   gnulib module vfprintf-posix-tests

## begin gnulib module warn-on-use

BUILT_SOURCES += warn-on-use.h
# The warn-on-use.h that gets inserted into generated .h files is the same as
# build-aux/warn-on-use.h, except that it has the copyright header cut off.
warn-on-use.h: $(top_srcdir)/build-aux/warn-on-use.h
	$(AM_V_GEN)rm -f $@-t $@ && \
	sed -n -e '/^.ifndef/,$$p' \
	  < $(top_srcdir)/build-aux/warn-on-use.h \
	  > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += warn-on-use.h warn-on-use.h-t

WARN_ON_USE_H=warn-on-use.h

EXTRA_DIST += $(top_srcdir)/build-aux/warn-on-use.h

## end   gnulib module warn-on-use

## begin gnulib module wchar-tests

TESTS += test-wchar
check_PROGRAMS += test-wchar
EXTRA_DIST += test-wchar.c

## end   gnulib module wchar-tests

## begin gnulib module wcrtomb-tests

TESTS += test-wcrtomb.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-wcrtomb

EXTRA_DIST += test-wcrtomb.sh test-wcrtomb.c signature.h macros.h

## end   gnulib module wcrtomb-tests

## begin gnulib module wctob


EXTRA_DIST += wctob.c

EXTRA_libtests_a_SOURCES += wctob.c

## end   gnulib module wctob

## begin gnulib module wctype-tests

TESTS += test-wctype
check_PROGRAMS += test-wctype
EXTRA_DIST += test-wctype.c macros.h

## end   gnulib module wctype-tests

## begin gnulib module wcwidth-tests

TESTS += test-wcwidth
check_PROGRAMS += test-wcwidth

EXTRA_DIST += test-wcwidth.c signature.h macros.h

## end   gnulib module wcwidth-tests

## begin gnulib module xalloc-die-tests

TESTS += test-xalloc-die.sh
check_PROGRAMS += test-xalloc-die
test_xalloc_die_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-xalloc-die.c test-xalloc-die.sh init.sh

## end   gnulib module xalloc-die-tests

# Clean up after Solaris cc.
clean-local:
	rm -rf SunWS_cache

mostlyclean-local: mostlyclean-generic
	@for dir in '' $(MOSTLYCLEANDIRS); do \
	  if test -n "$$dir" && test -d $$dir; then \
	    echo "rmdir $$dir"; rmdir $$dir; \
	  fi; \
	done; \
	:
