#!/bin/bash

# Start/stop/restart tomcat service
# Called with 0 arguments will start a stopped service
# or stop a running service.  You can also specify
# start/stop/restart to get the expected action
function tomcat 
{
    argc=$#

    case $argc in
        0)
            sudo /usr/sbin/service tomcat6 status >/dev/null 2>&1
            if (( $? == 0 )); then
                sudo /usr/sbin/service tomcat6 stop
            else
                sudo /usr/sbin/service tomcat6 start
            fi
            ;;
        1)
            sudo /usr/sbin/service tomcat6 $*
            ;;
        *)
            echo "Not a valid option...."
            echo "Usage: tomcat [start|stop|restart]"
            ;;
    esac
}
alias t='tomcat'

# Fuzzy cd
# Usage:
#    cdf public
# Changes to repos-public directory.
# http://dpaste.org/P59h/
function cdf
{
    cd *$1*/
}

function mvetest
{
    tomcat stop; alert
    pushd /home/djohnston/projects/mve >/dev/null 2>&1
    ./gradlew clean && ./gradlew platform:dm-mve:build; alert 
    tomcat start; alert
    popd >/dev/null 2>&1
    echo "Ready to test..."
}

function pm
{
    persist=
    while getopts ":p" opt
    do
        case $opt in
            p)
                persist=true
                ;;
            *)
                echo "Sorry, $opt is not valid.  Ignoring.."
                ;;
        esac
    done

    shift $((OPTIND-1))

    app=$@
    outDir=/home/djohnston/man_pdfs
    fn="${outDir}/${app}.pdf"
    man -t $app | ps2pdf - $fn
    /usr/bin/gnome-open $fn
    if [ ! $persist ]; then
        rm $fn
    fi
}
