" Special thanks to Drew Neil (http://github.com/nelstrom)
" Many settings came from his shownotes at vimcast.org
" Thanks, also, to David Johnston

set runtimepath+=$HOME/.vim/vimpdb
set runtimepath+=$HOME/.vim/pythoncomplete
runtime macros/matchit.vim
filetype off
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
let g:GetLatestVimScripts_allowautoinstall=1

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set nobackup
set nowb
set noswapfile

set history=50               " Keep 50 history items
set ruler                    " Always show cursor position
set showcmd                  " Show incorrect commands
set incsearch                " Start searching immediately

" for ubuntu
" set t_Co=256

" Don't use Ex mode, use Q for formatting
map Q gq

" Window resizing
map - <C-W>-
map = <C-W>+

" Task list
map <leader>td <Plug>TaskList

" Make green
map <leader>mg <Plug>MakeGreen

" Window controls
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" gundo
map <leader>g :GundoToggle<CR>

" pyflakes
let g:pyflakes_use_quickfix = 0

" pep8
let g:pep8_map='<leader>8'

" rope
map <leader>j :RopeGotoDefinition<CR>
map <leader>r :RopeRename<CR>

" ack
nmap <leader>a <Esc>:Ack!

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif


" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype on
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent    " always set autoindenting on

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
      \ | wincmd p | diffthis
endif

set visualbell t_vb=
set foldmethod=indent
set foldlevel=99
set number
set cursorline
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set hidden
set nojoinspaces
set listchars=tab:▸\ ,eol:¬
set wildmode=longest,list
set laststatus=2
set statusline=%F%m%r%h%w
set statusline+=\ %{fugitive#statusline()}
set statusline+=\ [%{strlen(&fenc)?&fenc:&enc}]
set statusline+=\ [line\ %l\/%L]

" Put swap files in /tmp file
" set backupdir=~/tmp
set directory=~/tmp
if has("autocmd")
  " autocmd FileType html,css,scss,ruby,pml,yaml,coffee,vim setlocal expandtab
  autocmd FileType python,javascript setlocal list
  autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
endif
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

let mapleader = ","
nmap <silent> <leader>l :set list!<CR>
nmap <silent> <leader>w :set wrap!<CR>
nmap <silent> <buffer> <leader>s :set spell!<CR>
nmap <silent> <leader>n :silent :nohlsearch<CR>

" Exuberant ctags
set tags=$VIM_CTAGS_PROJECT_DIR


" Vim-Latex
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'
au FileType tex so ~/.vim/ftplugin/tex_latexSuite.vim

" Fuzzy
map <leader>f :FufFileWithCurrentBufferDir **/<C-M>


" Toggle line numbers and fold column for easy copying:
nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>

color molokai
